name: CMake

on:
  push:
    branches: ["main, development", "haa/github-action-cmake"]
  pull_request:
    branches: ["main, development"]
jobs:
  build:
      strategy:
        matrix:
          # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
          build: [Release, Debug]
          os: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        # Configure CMake START
        - name: Configure CMake (Windows)
          if: ${{ (matrix.OS == 'windows-latest') }}
          shell: bash
          run: |
            cmake -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=${{matrix.build}}

        - name: Configure CMake (Linux)
          if: ${{ (matrix.OS == 'ubuntu-latest') }}
          shell: bash
          run: |
            cmake -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=${{matrix.build}}
        # Configure CMake END
        
        # Build CMake START
        - name: Build DreamEngine (Windows)
          if: ${{ (matrix.OS == 'windows-latest') }}
          shell: bash
          run: cmake --build "${{github.workspace}}/build" --config ${{matrix.build}} -j

        - name: Build DreamEngine (Linux)
          if: ${{ (matrix.OS == 'ubuntu-latest') }}
          shell: bash
          run: cmake --build "${{github.workspace}}/build --config ${{matrix.build}} -j"
        # Build CMake END
